services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: armarium
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: armarium_dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
